name: Pull request service labeling
on:
    - pull_request

jobs:
  pr-labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - run: |
         {
            # Parse changeset
            # SERVICES=$(cat ./*.md | grep -oP '^"\S+": (patch|minor|major)$' | grep -oP "\"\K.+(?=\")" | grep -v '^@')
            IN_PLACE_LABELS=${{ github.event.pull_request.labels.*.name }}
            echo "$SERVICES"
         } >> "$GITHUB_OUTPUT"

